
DROP TABLE IF EXISTS Queue;
DROP TABLE IF EXISTS VersionOfSong;
DROP TABLE IF EXISTS SongContributor;
DROP TABLE IF EXISTS Contributor;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Song;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Genre;









SELECT * FROM Queue;
SELECT * FROM VersionOfSong;
SELECT * FROM SongContributor;
SELECT * FROM Contributor;
SELECT * FROM Role;
SELECT * FROM User;
SELECT * FROM Genre;
SELECT * FROM Artist;
SELECT * FROM Song;


